name: xmagical-tests
on: [push, pull_request, workflow_dispatch]

jobs:
  run-xmagical-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image: ["python:3.8"]
    steps:
    - name: Checkout xmagical
      uses: actions/checkout@v2
    - name: Run tests in docker
      run: |
        docker run --mount "type=bind,src=$(pwd),dst=/tmp/xmagical" \
            -w "/tmp/xmagical" --rm ${{ matrix.docker-image }} /bin/bash test.sh