name: xmagical-tests
on: [push, pull_request, workflow_dispatch]

jobs:
  run-xmagical-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["python:3.11"]
    steps:
      - name: Checkout robopianist
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev gfortran libopenblas-dev liblapack-dev
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -e ".[test]"
      - name: Run tests
        run: |
          pytest tests/
